# PANDAS


In [1]:
import pandas as pd

In [2]:
a=pd.Series([1,2,9,6])#Series 1 dimension
print(a)

0    1
1    2
2    9
3    6
dtype: int64


In [3]:
print(type(a))

<class 'pandas.core.series.Series'>


In [4]:
a[2]

9

In [5]:
b=pd.Series([1,2,-12,67],index=['a','b','c','d'])
print(b)

a     1
b     2
c   -12
d    67
dtype: int64


In [6]:
print(b[2])
print(b['c'])

-12
-12


In [7]:
print(b[1:3])

b     2
c   -12
dtype: int64


In [8]:
print(b['a':'d'])

a     1
b     2
c   -12
d    67
dtype: int64


In [9]:
b['c']=12
b

a     1
b     2
c    12
d    67
dtype: int64

In [10]:
b[1]=69
b

a     1
b    69
c    12
d    67
dtype: int64

In [11]:
del b['d']
b

a     1
b    69
c    12
dtype: int64

In [12]:
c=pd.Series([12,5,6,22])
print(c>10)

0     True
1    False
2    False
3     True
dtype: bool


In [13]:
c=pd.Series([12,5,6,22])
print(c[c>10])

0    12
3    22
dtype: int64


In [14]:
c

0    12
1     5
2     6
3    22
dtype: int64

In [15]:
d=c+2
d

0    14
1     7
2     8
3    24
dtype: int64

In [16]:
g=pd.Series([1,0,2,1,2,3],
           index=['white','white','blue',
                 'green','green','yellow'])
print(g)
print(g.unique())
print(g.value_counts())
print(g.isin([0,3]))
print(g[g.isin([0,3])])

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64
[1 0 2 3]
1    2
2    2
0    1
3    1
dtype: int64
white     False
white      True
blue      False
green     False
green     False
yellow     True
dtype: bool
white     0
yellow    3
dtype: int64


In [17]:
data={'state':['ker','ker','kar','kar','kar'],
     'year':[2000,2001,2002,2003,2004],
     'pop':[1.5,1.7,3.6,2.4,2.9]}
data

{'state': ['ker', 'ker', 'kar', 'kar', 'kar'],
 'year': [2000, 2001, 2002, 2003, 2004],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [18]:
df=pd.DataFrame(data)
df

state  year  pop
0   ker  2000  1.5
1   ker  2001  1.7
2   kar  2002  3.6
3   kar  2003  2.4
4   kar  2004  2.9

In [19]:
df['year']

0    2000
1    2001
2    2002
3    2003
4    2004
Name: year, dtype: int64

In [20]:
df.year

0    2000
1    2001
2    2002
3    2003
4    2004
Name: year, dtype: int64

In [21]:
df[['year','state']]

year state
0  2000   ker
1  2001   ker
2  2002   kar
3  2003   kar
4  2004   kar

In [22]:
df['state'].unique()

array(['ker', 'kar'], dtype=object)

In [23]:
df['state'].nunique()

2

In [24]:
df.shape

(5, 3)

In [25]:
df

state  year  pop
0   ker  2000  1.5
1   ker  2001  1.7
2   kar  2002  3.6
3   kar  2003  2.4
4   kar  2004  2.9

In [26]:
df.loc[3]

state     kar
year     2003
pop       2.4
Name: 3, dtype: object

In [27]:
df.loc[1:3]

state  year  pop
1   ker  2001  1.7
2   kar  2002  3.6
3   kar  2003  2.4

In [28]:
import numpy as np

In [29]:
1+2+3+ np.NaN

nan

In [30]:
data= pd.Series([1, np.NaN, 3.5 , np.NaN,7])#NaN ->not a number =missing values
print(data)

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64


In [31]:
data.isnull()

0    False
1     True
2    False
3     True
4    False
dtype: bool

In [32]:
data[data.isnull()]

1   NaN
3   NaN
dtype: float64

In [33]:
data.isnull().sum()

2

In [34]:
data.notnull()


0     True
1    False
2     True
3    False
4     True
dtype: bool

In [35]:
print(data[data.notnull()])
print(data.notnull().sum())

0    1.0
2    3.5
4    7.0
dtype: float64
3


In [36]:
data1=data.dropna()

In [37]:
data1


0    1.0
2    3.5
4    7.0
dtype: float64

In [38]:
data


0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [39]:
data2=data.fillna(0)

In [40]:
data2

0    1.0
1    0.0
2    3.5
3    0.0
4    7.0
dtype: float64

In [41]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [42]:
data=pd.DataFrame([[1.0,6.5,3.0],
                  [1.0,np.NAN,np.NAN],
                  [np.NAN,np.NAN,np.NAN],
                  [np.NAN,6.5,3.0]])
print(data)

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0


In [43]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [44]:
data1=data.dropna()

In [45]:
data1

0    1    2
0  1.0  6.5  3.0

In [46]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [47]:
data2=data.dropna(how='all')
data2

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [48]:
data3=pd.DataFrame([[1.,np.NAN,3.],
                  [1.,np.NAN,np.NAN],
                  [np.NAN,np.NAN,np.NAN],
                  [np.NAN,np.NAN,3.]])
print(data3)

     0   1    2
0  1.0 NaN  3.0
1  1.0 NaN  NaN
2  NaN NaN  NaN
3  NaN NaN  3.0


In [49]:
data4=data3.dropna(how='all',axis=1)
data4

0    2
0  1.0  3.0
1  1.0  NaN
2  NaN  NaN
3  NaN  3.0

In [50]:
data5=data4.fillna({0:1,2:3})
data5

0    2
0  1.0  3.0
1  1.0  3.0
2  1.0  3.0
3  1.0  3.0

In [51]:
print(data4)
data4.fillna(0,inplace=True)
print(data4)

     0    2
0  1.0  3.0
1  1.0  NaN
2  NaN  NaN
3  NaN  3.0
     0    2
0  1.0  3.0
1  1.0  0.0
2  0.0  0.0
3  0.0  3.0


C:\Users\Asus\AppData\Local\Temp\ipykernel_6308\4128770249.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data4.fillna(0,inplace=True)


In [52]:
st1 = {'Subjects':['Maths','Sci','Eng','Hin'],
      'S1': [10,20,np.NaN,np.NaN],
      'S2': [5,np.NaN,np.NaN,29],
      'S3':[15,np.NaN,np.NaN,11],
      'S4':[21,22,23,25]}

#Create  a DataFrame from dictionary
df=pd.DataFrame(st1)
print(df)

  Subjects    S1    S2    S3  S4
0    Maths  10.0   5.0  15.0  21
1      Sci  20.0   NaN   NaN  22
2      Eng   NaN   NaN   NaN  23
3      Hin   NaN  29.0  11.0  25


In [53]:
df['S1'].fillna(value=df['S1'].mean(),inplace=True)
df

Subjects    S1    S2    S3  S4
0    Maths  10.0   5.0  15.0  21
1      Sci  20.0   NaN   NaN  22
2      Eng  15.0   NaN   NaN  23
3      Hin  15.0  29.0  11.0  25

In [54]:
df['S2'].fillna(value=df['S2'].mean(),inplace=True)
df

Subjects    S1    S2    S3  S4
0    Maths  10.0   5.0  15.0  21
1      Sci  20.0  17.0   NaN  22
2      Eng  15.0  17.0   NaN  23
3      Hin  15.0  29.0  11.0  25

In [55]:
df['S3'].fillna(value=df['S3'].mean(),inplace=True)
df

Subjects    S1    S2    S3  S4
0    Maths  10.0   5.0  15.0  21
1      Sci  20.0  17.0  13.0  22
2      Eng  15.0  17.0  13.0  23
3      Hin  15.0  29.0  11.0  25

In [60]:
#task
#1:
e=np.array([[0,10,20],
            [20,30,40]])
print(e)
    

[[ 0 10 20]
 [20 30 40]]


In [62]:
print(e[e>10])

[20 20 30 40]


In [63]:
#2
gh=np.full((3,5),2,dtype=int)
gh

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [65]:
#3
series1=pd.Series([2,4,6,8,10])#Series 1 dimension
print(series1)
series2=pd.Series([1,3,5,7,9])#Series 1 dimension
print(series2)

0     2
1     4
2     6
3     8
4    10
dtype: int64
0    1
1    3
2    5
3    7
4    9
dtype: int64


In [66]:
a=series1+series2
a

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [67]:
b=series1-series2
b

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [68]:
c=series1*series2
c

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [69]:
d=series1/series2
d

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64