In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
print("dtype",a.dtype)
print("ndim",a.ndim)
print("shape",a.shape)#no of col and rows
print("size",a.size)
print("itemsize",a.itemsize)#item size is number of bytes are allocated to ua integer value

int32
1
(5,)
5
4


In [9]:
b=np.array([[11,12,13],
          [21,22,23]])
print(b)
b.shape

[[11 12 13]
 [21 22 23]]


(2, 3)

In [10]:
print("dtype",b.dtype)
print("ndim",b.ndim)
print("shape",b.shape)#no of col and rows
print("size",b.size)
print("itemsize",b.itemsize)#item size is number of bytes are allocated to ua integer value

dtype int32
ndim 2
shape (2, 3)
size 6
itemsize 4


In [11]:
c=np.array([[1.0,2.0],
           [11.0,12.0],
            [21.5,22.36]])
print(c)

[[ 1.    2.  ]
 [11.   12.  ]
 [21.5  22.36]]


In [12]:
print("dtype",c.dtype)
print("ndim",c.ndim)
print("shape",c.shape)#no of col and rows
print("size",c.size)
print("itemsize",c.itemsize)#item size is number of bytes are allocated to ua integer value

dtype float64
ndim 2
shape (3, 2)
size 6
itemsize 8


In [13]:
d=np.array([[1],
            [2],
            [3]])
print(d)

[[1]
 [2]
 [3]]


In [14]:
print("dtype",d.dtype)
print("ndim",d.ndim)
print("shape",d.shape)#no of col and rows
print("size",d.size)
print("itemsize",d.itemsize)#item size is number of bytes are allocated to ua integer value

dtype int32
ndim 2
shape (3, 1)
size 3
itemsize 4


In [15]:
#create a ndarray with 3 rows and 3 columns
e=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print("dtype",e.dtype)
print("ndim",e.ndim)
print("shape",e.shape)#no of col and rows
print("size",e.size)
print("itemsize",e.itemsize)#item size is number of bytes are allocated to ua integer value

dtype int32
ndim 2
shape (3, 3)
size 9
itemsize 4


In [20]:
f=np.array([[1.25,2.25,3.35],
           [4.5,5.5,6.9]],dtype=int)
print(f)

[[1 2 3]
 [4 5 6]]


In [21]:
g=np.array([1,2,3,4],dtype=float)
print(g)
print(g.dtype)

[1. 2. 3. 4.]
float64


In [23]:
a=np.zeros(5,dtype=int)
print(a)

[0 0 0 0 0]


In [24]:
print(type(a))

<class 'numpy.ndarray'>


In [25]:
b=np.zeros((3,2),dtype=int)
print(b)

[[0 0]
 [0 0]
 [0 0]]


In [26]:
c=np.ones((2,3),dtype=int)
print(c)

[[1 1 1]
 [1 1 1]]


In [28]:
#create a 1 dim ndarry filled with ones dtype=float
d=np.ones(5)
print(d)

[1. 1. 1. 1. 1.]


In [30]:
gh=np.full((2,3),34,dtype=float)
gh

array([[34., 34., 34.],
       [34., 34., 34.]])

In [33]:
e=np.eye(4,dtype=int)
print(e)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [36]:
a=list(range(1,10,3))
print(a)


[1, 4, 7]


In [38]:
ab=tuple(range(1,10,3))
print(ab)


(1, 4, 7)


In [40]:
a=np.arange(1,21)
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>


In [41]:
a=np.arange(1,22,4)#here step value is 4
print(a)

[ 1  5  9 13 17 21]


In [42]:
a=np.arange(0,22,4)#here step value is 4
print(a)

[ 0  4  8 12 16 20]


In [43]:
c=np.arange(0,6,0.6)
print(c)

[0.  0.6 1.2 1.8 2.4 3.  3.6 4.2 4.8 5.4]


In [44]:
d=np.arange(1,17).reshape(4,4)
print(d)
print(type(d))
print(d.shape)
print(d.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
<class 'numpy.ndarray'>
(4, 4)
2


In [45]:
d=np.arange(20,36).reshape(8,2)
print(d)
print(d.size)

[[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]]
16


In [46]:
#Elementwise computation
b1 = np.arange(1,6)
print(b1)

[1 2 3 4 5]


In [47]:
b2 = b1+2
print("b2=",b2)
print("b1=",b1)

b2= [3 4 5 6 7]
b1= [1 2 3 4 5]


In [53]:
b3 = b1-2
b4=b1/2
b5=b1//2
b6=b1*2
b7=b1%2
b8=b1**2



In [57]:
print(b3)
print(b4)
print(b5)
print(b6)
print(b7)
print(b8)


[-1  0  1  2  3]
[0.5 1.  1.5 2.  2.5]
[0 1 1 2 2]
[ 2  4  6  8 10]
[1 0 1 0 1]
[ 1  4  9 16 25]


In [62]:
c1=np.arange(1,5).reshape(2,2)
print(c1)

c2=np.array([3,1,2,4]).reshape(2,2)
print(c2)

[[1 2]
 [3 4]]
[[3 1]
 [2 4]]


In [63]:
print(c1*c2)#element wise multiplication


[[ 3  2]
 [ 6 16]]


In [65]:
#Matrix multiplication
print(c1)
print(c2)
c3=np.dot(c1,c2)
print(c3)

[[1 2]
 [3 4]]
[[3 1]
 [2 4]]
[[ 7  9]
 [17 19]]


In [66]:
#Universal function'
x=np.arange(1,6)
print(x)

[1 2 3 4 5]


In [67]:
print(np.sqrt(x))
print(np.sin(x))
print(np.log(x))

[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [70]:
#Aggregrate function
print(np.sum(x))
print(np.min(x))
print(np.max(x))
print(np.mean(x))

15
1
5
3.0


In [71]:
#Indexing and slicing
y=np.arange(1,16)
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [72]:
print(y[5])

6


In [73]:
print(y[11])

12


In [76]:
print(y[3:11])

[ 4  5  6  7  8  9 10 11]


In [77]:
print(y)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [80]:
#1,3,5,7,9
print(y[:10:2])

[1 3 5 7 9]


In [88]:
print(y[4:10:5])

[ 5 10]


In [90]:
print(y[1::7])

[2 9]


In [91]:
print(y[[1,3,9,13]])

[ 2  4 10 14]


In [92]:
z=np.arange(1,17).reshape(4,4)
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [93]:
#5
print(z[1,0])#z(r,c)

5


In [95]:
print(z[1,2])
print(z[2,2])
print(z[2,1])
print(z[3,2])
print(z[3,0])

7
11
10
15
13


In [96]:
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [101]:
print(z[:,2])
print(z[:,1])

[ 3  7 11 15]
[ 2  6 10 14]


In [102]:
print(z[1,:])
print(z[3,:])

[5 6 7 8]
[13 14 15 16]


In [103]:
print(z[:,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [104]:
print(z[0:2,:])

[[1 2 3 4]
 [5 6 7 8]]


In [105]:
print(z[0:2,0:3])

[[1 2 3]
 [5 6 7]]


In [106]:
print(z[[0,2,3],:])

[[ 1  2  3  4]
 [ 9 10 11 12]
 [13 14 15 16]]


In [107]:
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [108]:
print(z[[1,3],1:3])

[[ 6  7]
 [14 15]]


In [113]:
print(z[:2,])

[[1 2 3 4]
 [5 6 7 8]]


In [112]:
print(z[0:2,:4])

[[1 2 3 4]
 [5 6 7 8]]


In [116]:
print(z[0:4,0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [118]:
print(z[:4,:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [119]:
print(z[:,[0,1,2]])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [120]:
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [124]:
print(z[1:3,1:3])

[[ 6  7]
 [10 11]]


In [125]:
print(z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [134]:
print(z[[1,3],::3])

[[ 5  8]
 [13 16]]
