In [1]:
import numpy as np

In [2]:
##random.random,random.randint,random.randn

In [6]:
a=np.random.random(3)#1 dimension +ve random value
print(a)
print(type(a))

[0.41235755 0.83021299 0.52860365]
<class 'numpy.ndarray'>


In [7]:
b=np.random.random((3,3))#two dimension random value
print(b)

[[0.65575111 0.73003473 0.84031717]
 [0.03355378 0.30245723 0.61084467]
 [0.16164306 0.27011519 0.61128482]]


In [8]:
c=np.random.randn(5)#1 dimension -ve value 
print(c)

[-0.03158434 -0.77048092 -0.78100697  1.02082732  0.86332473]


In [11]:
d=np.random.randn(4,4)
print(d)

[[ 0.3660072  -0.05322493  0.71617875  1.66347262]
 [ 0.49835075  0.02750755  0.56202167  0.7325143 ]
 [-0.11700643 -0.0786402  -1.07433066 -1.20950618]
 [ 0.81698494  0.62555756 -0.73696932 -1.12210741]]


In [27]:
e=np.random.randint(8)
print(e)

6


In [13]:
f=np.random.randint(0,8,5)
print(f)

[3 3 5 3 1]


In [14]:
g=np.random.randint(8,size=5)
print(g)

[5 2 1 5 6]


In [28]:
h=np.random.randint(8,size=50)
print(h)

[5 7 6 6 3 0 0 1 1 4 1 2 7 3 1 4 1 6 3 5 1 1 5 7 2 3 4 4 7 2 3 6 7 1 6 4 4
 3 5 0 0 5 4 3 2 2 7 4 1 4]


In [29]:
h1=np.random.randint(101,size=(4,4))
print(h1)

[[49 13 23 87]
 [87 80 96 11]
 [22 37 38 11]
 [96 78  1  2]]


# conditonal operators

In [30]:
i=np.random.random(6)
print(i)

[0.56161433 0.62050034 0.69860846 0.86460484 0.0690521  0.74394819]


In [31]:
print(i>0.5)

[ True  True  True  True False  True]


In [32]:
print(i[i>0.5])

[0.56161433 0.62050034 0.69860846 0.86460484 0.74394819]


In [33]:
print(i[i<0.5])

[0.0690521]


In [34]:
x=np.zeros((3,3),dtype=int)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [35]:
y=np.ones((3,3),dtype=int)
print(y)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [36]:
z=np.hstack((x,y))#merging as columns
print(z)

[[0 0 0 1 1 1]
 [0 0 0 1 1 1]
 [0 0 0 1 1 1]]


In [37]:
w=np.hstack((y,x))
print(w)

[[1 1 1 0 0 0]
 [1 1 1 0 0 0]
 [1 1 1 0 0 0]]


In [38]:
m=np.ones((2,3),dtype=int)
print(m)

[[1 1 1]
 [1 1 1]]


In [40]:
#n=np.hstack((m,x))#shape shd be same

In [41]:
p=np.vstack((x,y))#merge as rows
p

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### merge one dimensional ndarray

In [42]:
a=np.array([1,2,3])
b=np.array([14,15,16])
c=np.array([21,2,3])

In [43]:
d=np.row_stack((b,c,a))
d

array([[14, 15, 16],
       [21,  2,  3],
       [ 1,  2,  3]])

In [44]:
d1=np.column_stack((b,c,a))
d1

array([[14, 21,  1],
       [15,  2,  2],
       [16,  3,  3]])

# Split ndarray - symmetric and asymmetric

In [47]:
g = np.arange(1,17).reshape(4,4)
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
h,i=np.hsplit(g,2)  #splitting on columns
h


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [51]:
i

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [52]:
k,l=np.vsplit(g,2) #splitting on rows

In [53]:
k

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
l

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [55]:
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

np.split(g,[1,3])
(g,[0:1],[1:3],[3:])


In [56]:
x,y,z=np.split(g,[1,3])
x

array([[1, 2, 3, 4]])

In [57]:
y

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
z

array([[13, 14, 15, 16]])

In [59]:
g

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
a,b,c = np.split(g,[1,2])

In [61]:
a

array([[1, 2, 3, 4]])

In [62]:
b

array([[5, 6, 7, 8]])

In [63]:
c

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [64]:
a,b,c = np.split(g,[1,4])#0:1,1:4,4:

In [65]:
a

array([[1, 2, 3, 4]])

In [66]:
b

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [68]:
c

array([], shape=(0, 4), dtype=int32)

In [70]:
x,y,z= np.split(g,[1,3],axis=1)#for column

In [71]:
x

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [72]:
y

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [73]:
z

array([[ 4],
       [ 8],
       [12],
       [16]])

In [74]:
#m,n,l= np.split(g,[1,4],axis=1)#for column 0:1,1:4,4:

In [75]:
#m

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [76]:
#n

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [77]:
#l

array([], shape=(4, 0), dtype=int32)

In [82]:
x,y,z= np.split(g,[2,3],axis=1)

In [83]:
x

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [84]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [85]:
z

array([[ 4],
       [ 8],
       [12],
       [16]])

In [86]:
c,d=np.split(g,[1],axis=0)
c

array([[1, 2, 3, 4]])

In [87]:
d

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [94]:
e,f,i,g=np.split(g,[1,2,3],axis=0)
e

array([[1, 2, 3, 4]])

In [95]:
#TASK:

In [151]:
x=np.arange(1,37).reshape(6,6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
#1)create three arrays : a(row 0,1,2) b=3,c=4,5

In [127]:
a,b,c=np.split(x,[3,4])


In [128]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [129]:
b

array([[19, 20, 21, 22, 23, 24]])

In [130]:
c

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [132]:
x,y,z,r=np.split(x,[1,3,4])

In [133]:
x

array([[1, 2, 3, 4, 5, 6]])

In [134]:
y

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [135]:
z

array([[19, 20, 21, 22, 23, 24]])

In [136]:
r

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [145]:
#t,p=np.split(x,[3],axis=1)

In [146]:
t

array([[1, 2, 3]])

In [147]:
p

array([[4, 5, 6]])

In [152]:
m,n=np.hsplit(x,2)


In [153]:
print(m)

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]
 [25 26 27]
 [31 32 33]]


In [154]:
print(n)

[[ 4  5  6]
 [10 11 12]
 [16 17 18]
 [22 23 24]
 [28 29 30]
 [34 35 36]]


array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [160]:
r=np.arange(1,6)

In [161]:
r

array([1, 2, 3, 4, 5])

In [162]:
s=r

In [163]:
s

array([1, 2, 3, 4, 5])

In [165]:
r=np.arange(5,11)
r

array([ 5,  6,  7,  8,  9, 10])

In [166]:
s=r.copy()

In [167]:
r[0]=55
r

array([55,  6,  7,  8,  9, 10])

In [168]:
s

array([ 5,  6,  7,  8,  9, 10])

# PANDAS 

In [ ]:
#series and data frame (2 dimension)