In [3]:
import cv2 as cv
import numpy as np

In [2]:
%config IPCompleter.greedy=True

In [3]:
img= cv.imread("cat.jpg")
cv.imshow("Cat", img)
cv.waitKey(0)

-1

In [4]:
imgGray=  cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow('Gray', imgGray)
cv.waitKey(0)

-1

In [5]:
#cv.GaussianBlur(img,(kernel), sigma X))
imgBlur1= cv.GaussianBlur(img,(7,7),0)
imgBlur2= cv.GaussianBlur(imgGray,(7,7),0)

cv.imshow("Blur1",imgBlur1)
cv.imshow("Blur2",imgBlur2)
cv.waitKey(0)

-1

In [6]:
#cv.GaussianBlur(img,(kernel), sigma X))
imgBlur3= cv.GaussianBlur(img,(3,3),0)
imgBlur4= cv.GaussianBlur(img,(5,5),0)
imgBlur5= cv.GaussianBlur(img,(7,7),0)
imgBlur6= cv.GaussianBlur(img,(9,9),0)


cv.imshow("Blur3",imgBlur3)
cv.imshow("Blur4",imgBlur4)
cv.imshow("Blur5",imgBlur5)
cv.imshow("Blur6",imgBlur6)
cv.waitKey(0)

#typically to reduce image noise and reduce detail.

-1

In [7]:
#Detecting edges in an image

#cv.canny(img, lower_threshold, upper_threshold)

canny1 = cv.Canny(img,50,100)
canny2 = cv.Canny(imgGray,50,100)
canny3 = cv.Canny(imgBlur1,50,100)
cv.imshow("canny1",canny1)
cv.imshow("canny2",canny2)
cv.imshow("canny3",canny3)
cv.waitKey(0)

-1

In [8]:
#Note use blurred images for canny 
canny4=cv.Canny(imgBlur1,150,200)
cv.imshow("canny4",canny4)
cv.waitKey(0)

-1

### cv.canny(img, lower_threshold, upper_threshold)

High threshold is used to identify the strong pixels (intensity higher than the high threshold) 
Low threshold is used to identify the non-relevant pixels (intensity lower than the low threshold)

if the threshold is [50, 100] then the edge pixels above the upper limit(100) are considered and edge pixels below the threshold(50) are discarded.

#####  "what about the pixels in between upper and lower threshold"?
They are considered only if they are connected to pixels in the upper threshold. Thus we get a clean edge.

### Canny Edge Detector goes one step further and applies thresholding to remove the weakest edges and keep the strongest ones.

### Dilation : Increases the thickness of the edges

In [9]:
import numpy as np
kernel =np.ones((5,5), np.uint8)

#### uint8 implies the values can vary from 0 to 255

In [10]:
#use canny image

dilate1 = cv.dilate(canny4,kernel,iterations=1)
cv.imshow("dilate1",dilate1)
cv.imshow("canny4",canny4)
cv.waitKey(0)

-1

In [11]:
dilate2 = cv.dilate(canny4,kernel,iterations=2)
cv.imshow("dilate1",dilate2)
cv.imshow("canny4",canny4)
cv.waitKey(0)

-1

The opposite of dilation is erosion
Dilation adds pixels to the boundaries of objects in an image, 
while erosion removes pixels on object boundaries.

In [13]:
erode1 = cv.erode(dilate2,kernel,iterations=1)
cv.imshow("erode1",erode1)
cv.imshow("dilate2",dilate2)
cv.imshow("canny4",canny4)
cv.waitKey(0)

-1

In [14]:
erode2 = cv.erode(dilate2,kernel,iterations=2)
cv.imshow("erode1",erode2)
cv.imshow("dilate2",dilate2)
cv.waitKey(0)

-1

In [15]:
img.shape

(1415, 2120, 3)

(height, width, channels)  ie, (y,x,BGR)

In [16]:
blank1 = np.zeros((500,500))
cv.imshow('Blank1', blank1)
cv.waitKey(0)

-1

In [17]:
print(blank1)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [18]:
blank2 = np.zeros((500,500,3), dtype='uint8')#3-B=0,G=0,R=0
cv.imshow('Blank2', blank2)
cv.waitKey(0)

-1

In [17]:
print(blank2)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [19]:
blank3 = np.full((500,500),255, dtype='uint8')#255-white
cv.imshow('Blank3', blank3)
cv.waitKey(0)

-1

In [21]:
blank4 = np.zeros((500,500,3), dtype='uint8')#255-white
blank4[:]= 100,250,100
cv.imshow('Blank4', blank4)
cv.waitKey(0)

-1

In [22]:
blank = np.zeros((500,500,3), dtype='uint8')
#blank[y1:y2, x1:x2]
blank[120:300, 130:400] = 120, 255, 160  #B=120, G= 255, R=160
cv.imshow('Color', blank)
cv.waitKey(0)

-1

In [23]:
# Draw a line
# cv2.line(image, start_point(y1,x1), end_point(y2,x2), color, thickness)
blank = np.zeros((500,500,3), dtype='uint8')

cv.line(blank, (0,0), (300,250), (0,255,0), thickness=3)
cv.imshow('Line', blank)
cv.waitKey(0)

-1

In [25]:
cv.line(img, (0,0), (300,250), (0,255,0), thickness=3)
cv.imshow('Line', img)
cv.waitKey(0)

-1

In [26]:
# Draw a line
# cv2.line(image, start_point(y1,x1), end_point(y2,x2), color, thickness)
blank = np.zeros((500,500,3), dtype='uint8')

cv.line(blank, (0,0), (blank.shape[1],blank.shape[0]), (255,0,0), 
        thickness=3)

cv.imshow('Line', blank)
cv.waitKey(0)

-1

In [27]:
# Draw a line
# cv2.line(image, start_point(y1,x1), end_point(y2,x2), color, thickness)
blank = np.zeros((500,500,3), dtype='uint8')

cv.line(blank, (100,250), (300,400), (255,255,255), thickness=3)

cv.line(blank, (10,25), (150,240), (255,0,100),  thickness=3)

cv.imshow('Line', blank)
cv.waitKey(0)

-1

In [31]:
blank_white = np.full((500,500,3),255, dtype='uint8')#255-white
cv.line(blank_white, (100,250), (300,400), (0,0,255), thickness=3)
cv.imshow('blank_white', blank_white)
cv.waitKey(0)

#May not render properly on white background

-1

In [33]:
blank = np.zeros((500,500,3), dtype='uint8')

cv.arrowedLine(blank, (0,0), (300,250), (0,255,0), thickness=3)
cv.imshow('Line', blank)
cv.waitKey(0)

-1

In [34]:
blank = np.zeros((500,500,3), dtype='uint8')

cv.arrowedLine(blank, (300,250), (10,10), (0,255,0), thickness=3)
cv.imshow('Line', blank)
cv.waitKey(0)

-1

In [35]:
#Draw A Rectangle
blank = np.zeros((500,500,3), dtype='uint8')

cv.rectangle(blank, (50,50), (blank.shape[1]//2, blank.shape[0]//2), 
             (0,255,0), thickness=2)

cv.imshow('Rectangle', blank)
cv.waitKey(0)

-1

In [36]:
blank = np.zeros((500,500,3), dtype='uint8')

cv.rectangle(blank, (50,50), (blank.shape[1]//2, blank.shape[0]//2), 
             (0,255,0), thickness=-1)

cv.imshow('Rectangle', blank)
cv.waitKey(0)

-1

In [37]:
#When blank is not re-initialized

cv.line(blank, (10,25), (150,240), (255,0,100),  thickness=3)

cv.imshow('Line', blank)
cv.waitKey(0)


-1

In [39]:
img= cv.imread("cat.jpg")
cv.rectangle(img, (240,60),(425,250), (255,0,0), thickness=3)

cv.imshow('Rectangle', img)
cv.waitKey(0)

-1

In [40]:
# Draw A circle
# cv2.circle(image, center_coordinates, radius, color, thickness)
blank = np.zeros((500,500,3), dtype='uint8')
cv.circle(blank, (250, 250),150, (0,0,255),thickness=2)

cv.imshow('Circle', blank)
cv.waitKey(0)

-1

In [41]:
blank = np.zeros((500,500,3), dtype='uint8')
cv.circle(blank, (250, 250),100, (0,0,255),thickness=-1)

cv.imshow('Circle', blank)
cv.waitKey(0)

-1

In [42]:

# Draw a line
# cv2.line(image, start_point(y1,x1), end_point(y2,x2), color, thickness)
blank = np.zeros((500,500,3), dtype='uint8')

cv.line(blank, (100,250), (300,400), (255,255,255), thickness=3)

cv.line(blank, (10,25), (150,240), (255,0,100),  thickness=3)

cv.imshow('Line', blank)
cv.waitKey(0)

-1

In [44]:
# 5. Write text
#cv2.putText(image, text, org, font, fontScale, color[, thickness
#[, lineType[, bottomLeftOrigin]]])

blank = np.zeros((1100,1100,3), dtype='uint8')

cv.putText(blank, 'Hello, This is TRIPLEX', (0,225), 
           cv.FONT_HERSHEY_TRIPLEX,2.0, (0,255,0), 2)

cv.putText(blank, 'Hello, This is SIMPLEX', (0,100), 
           cv.FONT_HERSHEY_SIMPLEX,0.5, (0,255,0), 2)

cv.putText(blank, 'Hello, This is PLAIN', (0,355),  
           cv.FONT_HERSHEY_PLAIN,2.7, (0,255,0), 2)


cv.imshow('Text', blank)
cv.waitKey(0)


#FONT_HERSHEY_TRIPLEX
#FONT_HERSHEY_SIMPLEX
#FONT_HERSHEY_PLAIN


-1

## Joining Images

In [45]:
img= cv.imread("cat.jpg")
cv.imshow("Cat", img)
cv.waitKey(0)

-1

In [46]:
horizontal = np.hstack((img,img))
cv.imshow("horizontal", horizontal)
cv.waitKey(0)

-1

In [49]:
img2 = cv.imread("dog.jpg")
cv.imshow("Dog", img2)
cv.waitKey(0)

-1

In [51]:
#shape of both images should be same
horizontal2 = np.hstack((img2,img2))
cv.imshow("horizontal2", horizontal2)
cv.waitKey(0)

-1

In [53]:
#shape of both images should be same
vertical = np.vstack((img,img))
cv.imshow("vertical",vertical)
cv.waitKey(0)

-1

we cannot resize the image
one gray and one rgb cannot be joined
shape should be similar

In [54]:
blank = np.zeros((400,400), dtype='uint8')

rectangle = cv.rectangle(blank.copy(), (30,30), (370,370),255, -1)
cv.imshow('Rectangle', rectangle)
cv.waitKey(0)

circle = cv.circle(blank.copy(), (200,200), 200, 255,-1)
cv.imshow('Circle', circle)
cv.waitKey(0)

# bitwise AND --> intersecting regions
bit_and = cv.bitwise_and(rectangle, circle)

cv.imshow('Bitwise AND', bit_and)
cv.waitKey(0)

-1

In [55]:
# bitwise OR --> non-intersecting and intersecting regions
bit_or = cv.bitwise_or(rectangle, circle)
cv.imshow('Bitwise OR', bit_or)
cv.waitKey(0)

-1

In [56]:
# bitwise XOR --> non-intersecting regions
bit_xor = cv.bitwise_xor(rectangle, circle)
cv.imshow('Bitwise XOR', bit_xor)
cv.waitKey(0)

-1

In [57]:
# bitwise NOT
bit_not = cv.bitwise_not(circle)
cv.imshow('Circle NOT', bit_not)
cv.waitKey(0)

-1

In [5]:
img= cv.imread("dog.jpg")
cv.imshow("dog", img)
cv.waitKey(0)

-1

In [6]:
#canvas equivalent to image resolution
blank = np.zeros(img.shape[:2],dtype='uint8')
cv.imshow('Blank Image',blank)
cv.waitKey(0)

circle = cv.circle(blank.copy(),(img.shape[1]//2, img.shape[0]//2),100,255,-1)

rectangle = cv.rectangle(blank.copy(),(30,30),(370,370),255,-1)

weird_shape = cv.bitwise_and(circle,rectangle)

cv.imshow('Circle',circle)
cv.imshow('Rectangle',rectangle)
cv.imshow('Weird Shape',weird_shape)
cv.waitKey(0)



-1

In [7]:
masked=cv.bitwise_and(img,img,mask=weird_shape)
cv.imshow('Weired Shaped masked image',masked)
cv.waitKey(0)

-1

In [11]:
img = cv.imread("dog.jpg")

## convert to hsv
hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)

## mask of green (36,0,0) ~ (70, 255,255)
mask1 = cv.inRange(hsv, (36, 0, 0), (70, 255,255))

## mask of yellow (15,0,0) ~ (36, 255, 255)
mask2 = cv.inRange(hsv, (15,0,0), (36, 255, 255))

## final mask and masked
mask = cv.bitwise_or(mask1, mask2)
target = cv.bitwise_and(img,img, mask=mask)


cv.imshow("dog", img)
cv.imshow("Mask", target)
cv.waitKey(0)

cv.imwrite("target.png", target)#save ua image 



True

In [20]:
img = cv.imread("dog.jpg")

## convert to hsv
hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)

## mask of green (36,0,0) ~ (70, 255,255)
mask1 = cv.inRange(hsv, (110,50,50), (130,255,255))

## mask of yellow (15,0,0) ~ (36, 255, 255)
mask2 = cv.inRange(hsv, (0,100,100), (10,255,255))

## final mask and masked
mask = cv.bitwise_or(mask1, mask2)
target = cv.bitwise_and(img,img, mask=mask)


cv.imshow("dog", img)
cv.imshow("Mask", target)
cv.waitKey(0)

cv.imwrite("target.png", target)#save ua image 

True

In [25]:
vid = cv.VideoCapture(0)
while True:
    ret, frame = vid.read()
    cv.imshow("Original Frame",frame)
    
    hsv = cv.cvtColor(frame,cv.COLOR_BGR2HSV)
    cv.imshow("HSV Frame",hsv)
    
    mask = cv.inRange(hsv,(36, 0, 0),(70, 255,255))
    target=cv.bitwise_and(frame,frame,mask=mask)
    cv.imshow("Mask Frame",target)
    
    if cv.waitKey(1) == ord('q'):
        break
        
vid.release()
cv.destroyAllWindows()


In [30]:

vid = cv.VideoCapture(0)
while True:
    ret, frame = vid.read()
    cv.imshow("Original Frame",frame)
    
    hsv = cv.cvtColor(frame,cv.COLOR_BGR2HSV)
    cv.imshow("HSV Frame",hsv)
    mask1 = cv.inRange(hsv,(110,50,50),(130,255,255))
    mask2 = cv.inRange(hsv,(0,100,100),(10,255,255))
    target=cv.bitwise_and(frame,frame,mask=mask)
   
    cv.imshow("Mask Frame",target)
   
    mask = cv.bitwise_or(mask1, mask2)
    if cv.waitKey(1) == ord('q'):
        break
        
vid.release()
cv.destroyAllWindows()

In [ ]:
lower_blue = np.array([110,50,50])
upper_blue = np.array([130,255,255])

lower_red = np.array([0,100,100])
upper_red = np.array([10,255,255])
## mask of green (36,0,0) ~ (70, 255,255)
mask1 = cv.inRange(hsv, (36, 0, 0), (70, 255,255))

## mask of yellow (15,0,0) ~ (36, 255, 255)
mask2 = cv.inRange(hsv, (15,0,0), (36, 255, 255))